# Повторение примеров

## Поэлементные операции над многомерными массивами

In [2]:
# Массив 4x3 со случайными целыми числами (от 1 до 20):
a = rand(1:20,(4,3))

4×3 Matrix{Int64}:
  1   1  16
  1   8   4
 18   6  17
  7  14   7

In [3]:
# Поэлементная сумма:
sum(a)

100

In [4]:
# Поэлементная сумма по столбцам:
sum(a,dims=1)

1×3 Matrix{Int64}:
 27  29  44

In [5]:
# Поэлементная сумма по строкам:
sum(a,dims=2)

4×1 Matrix{Int64}:
 18
 13
 41
 28

In [6]:
# Поэлементное произведение:
prod(a)

644861952

In [7]:
# Поэлементное произведение по столбцам:
prod(a,dims=1)

1×3 Matrix{Int64}:
 126  672  7616

In [8]:
# Поэлементное произведение по строкам:
prod(a,dims=2)

4×1 Matrix{Int64}:
   16
   32
 1836
  686

In [9]:
using Statistics
# Вычисление среднего значения массива:
mean(a)

8.333333333333334

In [10]:
# Среднее по столбцам:
mean(a,dims=1)

1×3 Matrix{Float64}:
 6.75  7.25  11.0

In [11]:
# Среднее по строкам:
mean(a,dims=2)

4×1 Matrix{Float64}:
  6.0
  4.333333333333333
 13.666666666666666
  9.333333333333334

## Транспонирование, след, ранг, определитель и инверсия матрицы

In [12]:
using LinearAlgebra
# Массив 4x4 со случайными целыми числами (от 1 до 20):
b = rand(1:20,(4,4))

4×4 Matrix{Int64}:
  8  12  17   7
  4  16   4  18
 14  12  18  13
 14   4   4  14

In [13]:
# Транспонирование:
transpose(b)

4×4 transpose(::Matrix{Int64}) with eltype Int64:
  8   4  14  14
 12  16  12   4
 17   4  18   4
  7  18  13  14

In [14]:
# След матрицы (сумма диагональных элементов):
tr(b)

56

In [15]:
# Извлечение диагональных элементов как массив:
diag(b)

4-element Vector{Int64}:
  8
 16
 18
 14

In [16]:
# Ранг матрицы:
rank(b)

4

In [17]:
# Инверсия матрицы (определение обратной матрицы):
inv(b)

4×4 Matrix{Float64}:
  0.657534  -0.0742009   -0.696347   0.413242
  0.794521  -0.00285388  -0.834475   0.381279
 -0.506849   0.00684932   0.60274   -0.315068
 -0.739726   0.0730594    0.762557  -0.360731

In [18]:
# Определитель матрицы:
det(b)

3503.999999999998

In [19]:
# Псевдобратная функция для прямоугольных матриц:
pinv(a)

3×4 Matrix{Float64}:
 -0.0568629   -0.0280337    0.0629554    -0.0069
 -0.00993331   0.0414277   -0.0247167     0.059058
  0.0652247    0.00694845  -0.000784465  -0.00829325

## Вычисление нормы векторов и матриц, повороты, вращения

In [20]:
# Создание вектора X:
X = [2, 4, -5]

3-element Vector{Int64}:
  2
  4
 -5

In [21]:
# Вычисление евклидовой нормы:
norm(X)

6.708203932499369

In [22]:
# Вычисление p-нормы:
p = 1
norm(X,p)

11.0

In [23]:
# Расстояние между двумя векторами X и Y:
X = [2, 4, -5];
Y = [1,-1,3];
norm(X-Y)

9.486832980505138

In [24]:
# Проверка по базовому определению:
sqrt(sum((X-Y).^2))

9.486832980505138

In [25]:
# Угол между двумя векторами:
acos((transpose(X)*Y)/(norm(X)*norm(Y)))

2.4404307889469252

In [26]:
# Создание матрицы:
d = [5 -4 2 ; -1 2 3; -2 1 0]

3×3 Matrix{Int64}:
  5  -4  2
 -1   2  3
 -2   1  0

In [27]:
# Вычисление Евклидовой нормы:
opnorm(d)

7.147682841795258

In [28]:
# Вычисление p-нормы:
p=1
opnorm(d,p)

8.0

In [29]:
# Поворот на 180 градусов:
rot180(d)

3×3 Matrix{Int64}:
 0   1  -2
 3   2  -1
 2  -4   5

In [30]:
# Переворачивание строк:
reverse(d,dims=1)

3×3 Matrix{Int64}:
 -2   1  0
 -1   2  3
  5  -4  2

In [31]:
# Переворачивание столбцов
reverse(d,dims=2)

3×3 Matrix{Int64}:
 2  -4   5
 3   2  -1
 0   1  -2

## Матричное умножение, единичная матрица, скалярное произведение

In [32]:
# Матрица 2x3 со случайными целыми значениями от 1 до 10:
A = rand(1:10,(2,3))

2×3 Matrix{Int64}:
 8  5   8
 9  7  10

In [33]:
# Матрица 3x4 со случайными целыми значениями от 1 до 10:
B = rand(1:10,(3,4))

3×4 Matrix{Int64}:
 7   8  9  9
 5  10  9  8
 1   6  9  6

In [34]:
# Произведение матриц A и B:
A*B

2×4 Matrix{Int64}:
  89  162  189  160
 108  202  234  197

In [35]:
# Единичная матрица 3x3:
Matrix{Int}(I, 3, 3)

3×3 Matrix{Int64}:
 1  0  0
 0  1  0
 0  0  1

In [36]:
# Скалярное произведение векторов X и Y:
X = [2, 4, -5]
Y = [1,-1,3]
dot(X,Y)

-17

In [37]:
# тоже скалярное произведение:
X'Y

-17

## Факторизация. Специальные матричные структуры

In [38]:
# Задаём квадратную матрицу 3x3 со случайными значениями:
A = rand(3, 3)

3×3 Matrix{Float64}:
 0.162877  0.701688   0.438354
 0.402161  0.0982077  0.457615
 0.405168  0.528076   0.200503

In [39]:
# Задаём единичный вектор:
x = fill(1.0, 3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [40]:
# Задаём вектор b:
b = A*x

3-element Vector{Float64}:
 1.3029191742968955
 0.9579836390438312
 1.1337475715301344

In [41]:
# Решение исходного уравнения получаем с помощью функции \
# (убеждаемся, что x - единичный вектор):
A\b

3-element Vector{Float64}:
 1.0000000000000004
 0.9999999999999999
 0.9999999999999998

In [42]:
# LU-факторизация:
Alu = lu(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
 1.0        0.0      0.0
 0.402      1.0      0.0
 0.992579  -0.87035  1.0
U factor:
3×3 Matrix{Float64}:
 0.405168  0.528076  0.200503
 0.0       0.489401  0.357752
 0.0       0.0       0.569969

In [43]:
# Решение СЛАУ через матрицу A:
A\b

3-element Vector{Float64}:
 1.0000000000000004
 0.9999999999999999
 0.9999999999999998

In [44]:
# Решение СЛАУ через объект факторизации:
Alu\b

3-element Vector{Float64}:
 1.0000000000000004
 0.9999999999999999
 0.9999999999999998

In [45]:
# Детерминант матрицы A:
det(A)

0.11301873538996511

In [46]:
# Детерминант матрицы A через объект факторизации:
det(Alu)

0.11301873538996511

In [47]:
# QR-факторизация:
Aqr = qr(A)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor:
3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}:
 -0.274365   0.843755  -0.461304
 -0.677435  -0.510059  -0.530021
 -0.6825     0.167084   0.711532
R factor:
3×3 Matrix{Float64}:
 -0.593653  -0.61946   -0.567117
  0.0        0.630194   0.169954
  0.0        0.0       -0.302095

In [48]:
# Матрица Q:
Aqr.Q

3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}:
 -0.274365   0.843755  -0.461304
 -0.677435  -0.510059  -0.530021
 -0.6825     0.167084   0.711532

In [49]:
# Матрица R:
Aqr.R

3×3 Matrix{Float64}:
 -0.593653  -0.61946   -0.567117
  0.0        0.630194   0.169954
  0.0        0.0       -0.302095

In [50]:
# Проверка, что матрица Q - ортогональная:
Aqr.Q'*Aqr.Q

3×3 Matrix{Float64}:
 1.0          2.22045e-16  -2.22045e-16
 3.33067e-16  1.0           1.11022e-16
 0.0          5.55112e-17   1.0

In [51]:
# Симметризация матрицы A:
Asym = A + A'

3×3 Matrix{Float64}:
 0.325755  1.10385   0.843522
 1.10385   0.196415  0.985691
 0.843522  0.985691  0.401007

In [52]:
# Спектральное разложение симметризованной матрицы:
AsymEig = eigen(Asym)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
3-element Vector{Float64}:
 -0.8800576238910768
 -0.4600671197873084
  2.2633018521133477
vectors:
3×3 Matrix{Float64}:
  0.555542  -0.596011  -0.579779
 -0.794431  -0.174624  -0.581709
  0.245462   0.783758  -0.570501

In [53]:
# Собственные значения:
AsymEig.values

3-element Vector{Float64}:
 -0.8800576238910768
 -0.4600671197873084
  2.2633018521133477

In [54]:
#Собственные векторы:
AsymEig.vectors

3×3 Matrix{Float64}:
  0.555542  -0.596011  -0.579779
 -0.794431  -0.174624  -0.581709
  0.245462   0.783758  -0.570501

In [55]:
# Проверяем, что получится единичная матрица:
inv(AsymEig)*Asym

3×3 Matrix{Float64}:
  1.0          1.66533e-15  1.22125e-15
  7.77156e-16  1.0          9.4369e-16
 -2.22045e-16  4.44089e-16  1.0

In [56]:
# Матрица 1000 х 1000:
n = 1000
A = randn(n,n)

1000×1000 Matrix{Float64}:
  0.819247    1.3347     -0.87929   …  -1.66008    -0.921932   0.0764337
 -0.309981   -0.611186    0.31408       0.845723   -0.289022  -1.03657
  0.0424235   0.345224    1.39757      -1.08695    -0.143937   1.91639
 -1.62914    -0.753639   -1.49271       0.591753   -0.164626   1.79113
 -1.50272     0.746163    0.682439      0.601052    0.757437   0.445817
 -0.888618    0.450755   -1.64509   …   1.60036     1.19205    0.856004
 -0.925578    0.0226657  -0.587619     -3.47011     0.119459  -2.00127
  0.53807     0.809893   -1.03616       0.703836   -0.518179  -0.258721
 -0.579949    2.16316     0.562024     -0.121357   -1.36689   -0.00640057
 -1.59626    -1.43916    -1.53075       1.53479    -1.34931    1.04062
  0.567721    0.244734   -2.05328   …   0.178715   -0.263876   1.32741
 -0.912982    1.72539    -0.146148     -0.0229004   1.42372    1.52254
 -1.54976     2.37209     0.228364     -0.919874   -1.36234   -0.251655
  ⋮                                 ⋱    

In [57]:
# Симметризация матрицы:
Asym = A + A'

1000×1000 Matrix{Float64}:
  1.63849    1.02472   -0.836866    …  -1.80866     0.293468   0.726511
  1.02472   -1.22237    0.659304        1.8082     -0.362367  -0.741079
 -0.836866   0.659304   2.79514        -1.7594      0.597321   1.66348
 -1.14183   -1.28642   -1.0303          1.07173     0.068439   3.09274
 -1.21244    1.03349    0.386698        0.130618    2.80936    1.69901
 -0.366611  -0.798785  -2.08535     …   1.63735     2.02205    2.40125
 -2.02266    0.204185  -0.718416       -3.79614     1.60051   -2.63461
  0.68706    0.710628  -1.77431         1.18172     0.105465  -0.104329
 -0.615954   1.11954   -1.04574        -0.468595   -0.387612   1.3742
 -2.67528   -0.866521  -2.32624         1.21981    -0.194922   2.07119
 -1.55136    1.27545   -2.82866     …   0.154894    1.06473    0.85169
 -0.782705   2.4137    -0.00975513     -0.244604    2.42722    1.60479
 -2.23466    1.84357   -1.44457        -0.600433   -1.17243    0.0527268
  ⋮                                 ⋱         

In [58]:
# Проверка, является ли матрица симметричной:
issymmetric(Asym)

true

In [59]:
# Добавление шума:
Asym_noisy = copy(Asym)
Asym_noisy[1,2] += 5eps()
Asym_noisy

1000×1000 Matrix{Float64}:
  1.63849    1.02472   -0.836866    …  -1.80866     0.293468   0.726511
  1.02472   -1.22237    0.659304        1.8082     -0.362367  -0.741079
 -0.836866   0.659304   2.79514        -1.7594      0.597321   1.66348
 -1.14183   -1.28642   -1.0303          1.07173     0.068439   3.09274
 -1.21244    1.03349    0.386698        0.130618    2.80936    1.69901
 -0.366611  -0.798785  -2.08535     …   1.63735     2.02205    2.40125
 -2.02266    0.204185  -0.718416       -3.79614     1.60051   -2.63461
  0.68706    0.710628  -1.77431         1.18172     0.105465  -0.104329
 -0.615954   1.11954   -1.04574        -0.468595   -0.387612   1.3742
 -2.67528   -0.866521  -2.32624         1.21981    -0.194922   2.07119
 -1.55136    1.27545   -2.82866     …   0.154894    1.06473    0.85169
 -0.782705   2.4137    -0.00975513     -0.244604    2.42722    1.60479
 -2.23466    1.84357   -1.44457        -0.600433   -1.17243    0.0527268
  ⋮                                 ⋱         

In [60]:
# Проверка, является ли матрица симметричной:
issymmetric(Asym_noisy)

false

In [61]:
# Явно указываем, что матрица является симметричной:
Asym_explicit = Symmetric(Asym_noisy)

1000×1000 Symmetric{Float64, Matrix{Float64}}:
  1.63849    1.02472   -0.836866    …  -1.80866     0.293468   0.726511
  1.02472   -1.22237    0.659304        1.8082     -0.362367  -0.741079
 -0.836866   0.659304   2.79514        -1.7594      0.597321   1.66348
 -1.14183   -1.28642   -1.0303          1.07173     0.068439   3.09274
 -1.21244    1.03349    0.386698        0.130618    2.80936    1.69901
 -0.366611  -0.798785  -2.08535     …   1.63735     2.02205    2.40125
 -2.02266    0.204185  -0.718416       -3.79614     1.60051   -2.63461
  0.68706    0.710628  -1.77431         1.18172     0.105465  -0.104329
 -0.615954   1.11954   -1.04574        -0.468595   -0.387612   1.3742
 -2.67528   -0.866521  -2.32624         1.21981    -0.194922   2.07119
 -1.55136    1.27545   -2.82866     …   0.154894    1.06473    0.85169
 -0.782705   2.4137    -0.00975513     -0.244604    2.42722    1.60479
 -2.23466    1.84357   -1.44457        -0.600433   -1.17243    0.0527268
  ⋮                       

In [62]:
using BenchmarkTools
# Оценка эффективности выполнения операции по нахождению
# собственных значений симметризованной матрицы:
@btime eigvals(Asym);
# Оценка эффективности выполнения операции по нахождению
# собственных значений зашумлённой матрицы:
@btime eigvals(Asym_noisy);
# Оценка эффективности выполнения операции по нахождению
# собственных значений зашумлённой матрицы,
# для которой явно указано, что она симметричная:
@btime eigvals(Asym_explicit);

  186.976 ms (11 allocations: 7.99 MiB)
  772.360 ms (14 allocations: 7.93 MiB)
  192.327 ms (11 allocations: 7.99 MiB)


In [63]:
# Трёхдиагональная матрица 1000000 х 1000000:
n = 1000000;
A = SymTridiagonal(randn(n), randn(n-1))

1000000×1000000 SymTridiagonal{Float64, Vector{Float64}}:
 0.272681   2.73483     ⋅        …    ⋅          ⋅          ⋅ 
 2.73483    1.51212   -0.731553       ⋅          ⋅          ⋅ 
  ⋅        -0.731553   0.271751       ⋅          ⋅          ⋅ 
  ⋅          ⋅         0.429758       ⋅          ⋅          ⋅ 
  ⋅          ⋅          ⋅             ⋅          ⋅          ⋅ 
  ⋅          ⋅          ⋅        …    ⋅          ⋅          ⋅ 
  ⋅          ⋅          ⋅             ⋅          ⋅          ⋅ 
  ⋅          ⋅          ⋅             ⋅          ⋅          ⋅ 
  ⋅          ⋅          ⋅             ⋅          ⋅          ⋅ 
  ⋅          ⋅          ⋅             ⋅          ⋅          ⋅ 
  ⋅          ⋅          ⋅        …    ⋅          ⋅          ⋅ 
  ⋅          ⋅          ⋅             ⋅          ⋅          ⋅ 
  ⋅          ⋅          ⋅             ⋅          ⋅          ⋅ 
 ⋮                               ⋱                        
  ⋅          ⋅          ⋅             ⋅          ⋅          ⋅ 
 

In [64]:
# Оценка эффективности выполнения операции по нахождению
# собственных значений:
@btime eigmax(A)

  548.205 ms (17 allocations: 183.11 MiB)


6.392585152921395

In [65]:
B = Matrix(A)

LoadError: OutOfMemoryError()

## Общая линейная алгебра

In [66]:
# Матрица с рациональными элементами:
Arational = Matrix{Rational{BigInt}}(rand(1:10, 3, 3))/10

3×3 Matrix{Rational{BigInt}}:
 3//10  7//10  1//10
 3//10  7//10  9//10
 1//2   1//5   9//10

In [67]:
# Единичный вектор:
x = fill(1, 3)

3-element Vector{Int64}:
 1
 1
 1

In [68]:
# Задаём вектор b:
b = Arational*x

3-element Vector{Rational{BigInt}}:
 11//10
 19//10
  8//5

In [69]:
# Решение исходного уравнения получаем с помощью функции \
# (убеждаемся, что x - единичный вектор):
Arational\b

3-element Vector{Rational{BigInt}}:
 1//1
 1//1
 1//1

In [70]:
# LU-разложение:
lu(Arational)

LU{Rational{BigInt}, Matrix{Rational{BigInt}}, Vector{Int64}}
L factor:
3×3 Matrix{Rational{BigInt}}:
 1//1  0//1  0//1
 3//5  1//1  0//1
 3//5  1//1  1//1
U factor:
3×3 Matrix{Rational{BigInt}}:
 1//2   1//5    9//10
 0//1  29//50   9//25
 0//1   0//1   -4//5

# Самостоятельная работа

## 1. Произведение векторов

### 1. Задайте вектор v. Умножьте вектор v скалярно сам на себя и сохраните результат в dot_v

In [71]:
v = rand(1:100, 3); display(v)
dot_v = v'v

3-element Vector{Int64}:
 76
 62
 35

10845

### 2. Умножьте v матрично на себя (внешнее произведение), присвоив результат переменной outer_v.

In [72]:
outer_v = v*v'

3×3 Matrix{Int64}:
 5776  4712  2660
 4712  3844  2170
 2660  2170  1225

## 2. Системы линейных уравнений

### 1. Решить СЛАУ с двумя неизвестными.

In [73]:
function LinearDep(mtrx::Matrix, vec::Vector)
    # returns isSolvable::Bool, ind::Vector{Int64} -- вектор 
    A = hcat(mtrx, vec)
    Ac = copy(mtrx); bc = copy(vec)
    s1 = size(A)[1]; s2 = size(A)[2]-1
    t = [false for i in 1:size(A)[1]]
    poss_j = collect(2:s2)
    for i in 1:s2
        for j in i+1:s1
            mbool = true
            temp = A[j, :]./A[i, :]
            if length(unique(temp[1:s2])) == 1
                if temp[s2+1] == temp[1]
                    t[j] = true
                else
                    return false, []
                end
            end
            tii = i
            if Ac[i, i] == 0
                tii = sortperm(abs.(Ac[i, :]))[s2]
                if Ac[i, tii] == 0
                    mbool = false
                end
            end
            if mbool
                c = -Ac[j, tii] / Ac[i, tii]
                if isequal(Ac[j, :].+(c*Ac[i, :]), zeros(Float64, s2))
                    if bc[j] + c*bc[i] != 0
                        return false, []
                    else
                        t[j] = true
                        Ac[j, :] = Ac[j, :].+(c*Ac[i, :])
                        bc[j] += c*bc[i]
                    end
                else
                    Ac[j, :].+= (c*Ac[i, :])
                    bc[j] += c*bc[i]
                end
            end
        end
    end
    for i in 1:s1
        if isequal(Ac[i, :], zeros(Float64, s2))
            t[i] = true
        end
    end
    answ = deleteat!(collect(1:s1), t)
    if length(answ) >= s2
        return true, answ
    else 
        return false, [pi]
    end
end

function SLAU_solver(A::Matrix, b::Vector)
    if ndims(A) != 2 || size(A)[1] != length(b)
        println("Не совпадают размерности!")
        return
    end
    s1 = size(A)[1]; s2 = size(A)[2]
    if s1 == s2 && det(A) != 0
        return A\b
    elseif s1 < s2
        println("Уравнений меньше, чем переменных")
        return
    else # s1 > s2 || (s1 == s2 && det(A) == 0)
        isSolvable, indNonLinear = LinearDep(A, b)
        if !isSolvable && isequal(indNonLinear, [])
            println("Нет решений")
            return
        elseif !isSolvable && isequal(indNonLinear, [pi])
            println("Бесконечное количество решений")
            return
        else 
            length(indNonLinear) > s2 ? indNonLinear = indNonLinear[1:s2] : 
            return A[indNonLinear, :]\b[indNonLinear]
        end
    end
end
A = Float64[1 2 3; 1/3 2 1; 2 3 6; 3 4 5]
b = Float64[1, 1, 4, 5]
SLAU_solver(A, b)

Нет решений


#### a)

$$
\begin{cases}
x+y=2,\\
x-y=3.
\end{cases}
$$

Решение существует (система линейно независима)

In [74]:
A = Float64[1 1; 1 -1]
b = Float64[2, 3]
SLAU_solver(A, b)

2-element Vector{Float64}:
  2.5
 -0.5

#### b)

$$
\begin{cases}
x+y=2,\\
2x+2y=4.
\end{cases}
$$

Бесконечное количество решений (вся система линейно зависима (и коэффициенты, и вектор ответов))

In [75]:
A = Float64[1 1; 2 2]
b = Float64[2, 4]
SLAU_solver(A, b)

Бесконечное количество решений


#### c)

$$
\begin{cases}
x+y=2,\\
2x+2y=5.
\end{cases}
$$

Решений нет (матрица коэффициентов линейно зависима, при этом векторы нет)

In [76]:
A = Float64[1 1; 2 2]
b = Float64[2, 5]
SLAU_solver(A, b)

Нет решений


#### d)

$$
\begin{cases}
x+y = 1,\\
2x+2y = 2,\\
3x+3y = 3.
\end{cases}
$$

Бесконечное количество решений аналитически (вся система линейно зависима)

In [77]:
A = Float64[1 1; 2 2; 3 3]
b = Float64[1, 2, 3]
SLAU_solver(A, b)

Бесконечное количество решений


#### e)

$$
\begin{cases}
x+y=2,\\
2x+y=1,\\
x-y=3.
\end{cases}
$$

In [78]:
A = Float64[1 1; 2 1; 1 -1]
b = Float64[2, 1, 3]
SLAU_solver(A, b)

Нет решений


#### f)

$$
\begin{cases}
x+y=2,\\
2x+y=1,\\
3x+2y=3.
\end{cases}
$$

In [79]:
A = Float64[1 1; 2 1; 3 2]
b = Float64[2, 1, 3]
SLAU_solver(A, b)

2-element Vector{Float64}:
 -1.0
  3.0

### 2. Решить СЛАУ с тремя неизвестными.

#### a)

$$
\begin{cases}
x+y+z=2,\\
x-y-2z=3.
\end{cases}
$$

In [80]:
A = Float64[1 1 1; 1 -1 -2]
b = Float64[2, 3]
SLAU_solver(A, b)

Уравнений меньше, чем переменных


#### b)

$$
\begin{cases}
x+y+z=2,\\
2x+2y-3z=3,\\
3x+y+z=1.
\end{cases}
$$

In [81]:
A = Float64[1 1 1; 2 2 -3; 3 1 1]
b = Float64[2, 4, 1]
SLAU_solver(A, b)

3-element Vector{Float64}:
 -0.5
  2.5
  0.0

#### c)

$$
\begin{cases}
x+y+z=1,\\
x+y+2z=0,\\
2x+2y+3z=1.
\end{cases}
$$

In [82]:
A = Float64[1 1 1; 1 1 2; 2 2 3]
b = Float64[1, 0, 1]
SLAU_solver(A, b)

Бесконечное количество решений


#### d)

$$
\begin{cases}
x+y+z=1,\\
x+y+2z=0,\\
2x+2y+3z=0.
\end{cases}
$$

In [83]:
A = Float64[1 1 1; 1 1 2; 2 2 3]
b = Float64[1, 0, 0]
SLAU_solver(A, b)

Нет решений


## 3. Операции с матрицами

In [84]:
function to_Diagonal(mtrx)
    s = size(mtrx)[1]
    ordDown = vcat([[if i == s; [i, j-1] else [i, j] end for j in i+1:s] for i in 1:s]...)
    ordUP = vcat([[if i == s; [j-1, i] else [j, i] end for j in i+1:s] for i in s:-1:1]...)
    answ = [[] for _ in 1:s]
    for i in ordDown
        if mtrx[i[2], i[1]] != 0
            k = mtrx[i[2], i[1]] / mtrx[i[1], i[1]]
            answ[i[2]] = [mtrx[i[2], j] - mtrx[i[1], j] * k for j in 1:s]
        end
    end
    for i in ordUP
        if mtrx[i[2], i[1]] != 0
            k = mtrx[i[2], i[1]] / mtrx[i[1], i[1]]
            answ[i[2]] = [mtrx[i[2], j] - mtrx[i[1], j] * k for j in 1:s]
        end
    end
    return copy(hcat(answ...)')
end

to_Diagonal (generic function with 1 method)

#### a)

In [85]:
A = Float64[1 -2; -2 1]
to_Diagonal(A)

2×2 Matrix{Float64}:
 -3.0   0.0
  0.0  -3.0

#### b)

In [86]:
A = Float64[1 -2; -2 3]
to_Diagonal(A)

2×2 Matrix{Float64}:
 -0.333333   0.0
  0.0       -1.0

#### c)

In [87]:
A = Float64[1 -2 0; -2 1 2; 0 2 0]
to_Diagonal(A)

3×3 Matrix{Float64}:
  -3.0    0.0    4.0
 NaN    -Inf   NaN
   4.0    0.0   -4.0

### 2. Вычислите

In [88]:
function mtrx_Function(A::Matrix, op)
    X = eigvecs(A)
    lamb = diagm(eigvals(A))
    lambfunc = [op(l) for l in lamb]
    answ = X^(-1)*lambfunc*X
    return answ
end

mtrx_Function (generic function with 1 method)

#### a)

In [89]:
A = [1 -2; -2 1]; display(A^10)
mtrx_Function(A, x -> x^10)

2×2 Matrix{Int64}:
  29525  -29524
 -29524   29525

2×2 Matrix{Float64}:
  29525.0  -29524.0
 -29524.0   29525.0

#### b)

In [90]:
A = [5 -2; -2 5]
mtrx_Function(A, x-> sqrt(x))

2×2 Matrix{Float64}:
  2.1889   -0.45685
 -0.45685   2.1889

#### c)

In [91]:
A = [1 -2; -2 1]
mtrx_Function(A, x-> cbrt(x))

2×2 Matrix{Float64}:
  0.221125  -1.22112
 -1.22112    0.221125

#### d)

In [92]:
A = ComplexF64[1 2; 3 4]
mtrx_Function(A, x-> sqrt(x))

2×2 Matrix{ComplexF64}:
 0.553689+0.464394im  -0.889962+0.234276im
 -1.09755+0.288922im    1.76413+0.145754im

### 3. Найдите собственные значения матрицы

In [93]:
A = [140 97 74 168 131; 97 106 89 131 36; 74 89 152 144 71; 168 131 144 52 142; 131 36 71 142 36]
@btime eigvals(A)

  4.329 μs (10 allocations: 2.59 KiB)


5-element Vector{Float64}:
 -129.84037845927043
  -56.00818131207859
   42.750686387437305
   87.15844501190587
  541.9394283720058

Создайте диагональную матрицу из собственных значений матрицы $A$. Создайте нижнедиагональную матрицу из матрицы $A$. Оцените эффективность выполняемых операций.

In [94]:
@btime diagm(eigvals(A))

  4.471 μs (11 allocations: 2.84 KiB)


5×5 Matrix{Float64}:
 -129.84    0.0      0.0      0.0       0.0
    0.0   -56.0082   0.0      0.0       0.0
    0.0     0.0     42.7507   0.0       0.0
    0.0     0.0      0.0     87.1584    0.0
    0.0     0.0      0.0      0.0     541.939

In [95]:
@btime blA = Bidiagonal(A, :L)

  249.171 ns (3 allocations: 224 bytes)


5×5 Bidiagonal{Int64, Vector{Int64}}:
 140    ⋅    ⋅    ⋅   ⋅
  97  106    ⋅    ⋅   ⋅
   ⋅   89  152    ⋅   ⋅
   ⋅    ⋅  144   52   ⋅
   ⋅    ⋅    ⋅  142  36